language: c
dist: trusty
compiler: gcc
stages:
- make
jobs:
  include:
  - stage: make
    script:
    - echo entering make stage \(compile, identify branch, clean\)
    - make
    - ls src/
    - echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - make clean
    - ls src/
    after_success: ./merge.sh
