language: c
dist: trusty
compiler: gcc
sudo: required
script: sudo apt-get install make
stages:
- make
jobs:
  include:
  - stage: make
    script:
    - make -v && gcc -v
    - echo entering make stage \(compile, identify branch, clean\)
    - ls src/
    - make
    - echo ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - ls src/
    after_success: ./merge.sh
